apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: worker
          image: ghcr.io/darkqpid/devops_agnos_assignment_worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: worker-config
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 15
            periodSeconds: 20