apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: prod
data:
  ENV: "prod"
  LOG_LEVEL: "warning"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: prod
data:
  ENV: "prod"
  WORKER_INTERVAL: "300"
  WORKER_MAX_FAILURES: "3"