apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: uat
data:
  ENV: "uat"
  LOG_LEVEL: "info"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: uat
data:
  ENV: "uat"
  WORKER_INTERVAL: "120"
  WORKER_MAX_FAILURES: "5"
  LOG_LEVEL: "info"        
  PYTHONUNBUFFERED: "1"